### ISSUE TITLE
Proposal: Use a more engineering-oriented error code wrapper.

### ISSUE THREAD

**Issue by ozline** [CocaineCong/tangseng#48]
Refer to [this juejin article](https://juejin.cn/post/7246777406387306553)

This is very suitable for some beginners of golang to contribute to this project, such as students who are being assessed in university studios.

**Comment by lyt122** [comment]
hello, I think I can solve this issue

**Comment by ozline** [comment]
I hope you can complete this task as soon as possible. Meanwhile, I wish you a happy end of term.

**Comment by CocaineCong** [comment]
@lyt122 pls comment here to fill in all the pr you have merged for record. 
btw, thanks for your all contributions.

**Comment by lyt122** [comment]
@CocaineCong Sure, here is a list of the merged Pull Requests:
#56: refactor: Use a more engineering-oriented error code wrapper
#57: refactor: Use a more engineering-oriented error code wrapper
#58: refactor: Use a more engineering-oriented error code wrapper
#59: refactor: Use a more engineering-oriented error code wrapper.
If you need more detailed information about my PR, feel free to ask. Thanks again for your help!"

**Comment by ozline** [comment]
> @CocaineCong Sure, here is a list of the merged Pull Requests: #56: refactor: Use a more engineering-oriented error code wrapper #57: refactor: Use a more engineering-oriented error code wrapper #58: refactor: Use a more engineering-oriented error code wrapper #59: refactor: Use a more engineering-oriented error code wrapper. If you need more detailed information about my PR, feel free to ask. Thanks again for your help!"

ha, you can quote this issue on your pr, you can find out how to do it yourself.
