### ISSUE TITLE
Feature Request:  Add Prometheus as project's monitor

### ISSUE THREAD

**Issue by ozline** [CocaineCong/tangseng#53]
# Background
This is a project that spans across go and python. We hope to provide certain observability for each request in order to monitor the project.

# Introduce of Prometheus
Prometheus is an open-source monitoring and alerting toolkit designed for reliability and scalability of applications. It was originally developed at SoundCloud and later open-sourced. Prometheus is part of the Cloud Native Computing Foundation (CNCF) and has gained widespread adoption in the container orchestration ecosystem, particularly with Kubernetes.

In the context of Go (Golang), Prometheus is often used with a Go client library that allows developers to instrument their Go applications for monitoring and exposing metrics. The official Prometheus Go client library provides a set of functions and utilities to help developers expose custom metrics from their Go applications and make them available for scraping by a Prometheus server.

# Problem Description

We hope to: integrate Prometheus for this project.

In fact, Prometheus also has a Python client SDK that allows for observability in Python projects.

# How to solve this problem

1. First, provide support for Prometheus in the Go language part of this project.
2. After completing the previous task, submit a PR for code review.
3. Once the code review is approved, if there is remaining time, provide support for Prometheus in the Python project.

**Comment by CocaineCong** [comment]
done
